export { default as AccountIcon } from "./Account";
export { default as ArrowRightDoubleIcon } from "./ArrowRightDouble";
export { default as CourseCertificateIcon } from "./CourseCertificate";
export { default as MinusIcon } from "./MinusIcon";
export { default as PlayIcon } from "./PlayIcon";
export { default as PlusIcon } from "./PlusIcon";
export { default as QnAIcon } from "./QnAIcon";
export { default as StarIcon } from "./StarIcon";
export { default as TickIcon } from "./TickIcon";
